- name: Debug use_https variable
  hosts: soufe1
  become: yes
  tasks:
    - name: debug variable
      debug:
        msg: "System {{ use_https }}"

- name: Configure soufe and soube nodes
  hosts: all
  become: yes
  roles:
    - sou_podman

- name: Configure HaProxy on soufe
  hosts: soufe1
  become: yes
  roles: 
    - sou_haProxy

- name: Configure Prometeus on soube
  hosts: soube1
  become: yes
  roles:
    - sou_prometheus

- name: Configure Grafana on soube
  hosts: soube1
  become: yes
  roles:
    - sou_grafana
