- name: Generate haproxy.cfg from template
  template:
    src: ../templates/haproxy.cfg.j2  
    dest: /tmp/haproxy.cfg  

- name: Copy SSL cert
  ansible.builtin.copy:
    src: ../certs/haproxy.pem
    dest: /tmp/haproxy.pem
    owner: root
    mode: 0777

- name: Install HAProxy via Podman
  containers.podman.podman_container:
    name: haproxy
    image: docker.io/library/haproxy:2.3
    state: started
    ports:
      - "8404:8404"
      - "8444:8444"
      - "8443:8443"
    volumes:
      - /tmp/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:Z  # Mount the config file
      - /tmp/haproxy.pem:/usr/local/etc/haproxy/certs/haproxy.pem:Z  # Mount cert
      - /tmp/haproxy.conf:/etc/rsyslog.d/haproxy.conf 
