- name: Create base directory for container volumes
  ansible.builtin.file:
    path: /containers_vols
    state: directory
    mode: '0755'

- name: Create Grafana data directory
  ansible.builtin.file:
    path: /containers_vols/grafana/data
    state: directory
    mode: '0777'

- name: Create Grafana config directory
  ansible.builtin.file:
    path: /containers_vols/grafana/config
    state: directory
    mode: '0777'

- name: Generate grafana.ini from template
  template:
    src: ../templates/grafana.ini.j2  
    dest: /containers_vols/grafana/config/grafana.ini

- name: Create Grafana container
  containers.podman.podman_container:
    name: grafana
    image: grafana/grafana
    state: started
    volumes:
      - /containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z
      - /containers_vols/grafana/data:/var/lib/grafana:z
    ports:
      - "3000:3000"

